import streamlit as st

def mostrar_resumenes():
    # Información de las secciones
    secciones = [
        {
            "titulo": ":bookmark_tabs: Estatutos FIFA",
            "resumen": [
                "Texto resumen Estatutos FIFA..."
            ]
        },
        {
            "titulo": ":orange_book: Código Disciplinario",
            "resumen": [
                ":orange[***Artículo 1 Objeto***:] \n\n1. Define las infracciones según la reglamentación de la FIFA.\n"
                "2. Establece sanciones para dichas infracciones.\n"
                "3. Regula la organización y funcionamiento de los órganos judiciales de la FIFA y los procedimientos a seguir.",
                ":orange[***Artículo 2 Ámbito de aplicación material***:] \n\n1. Aplicable a partidos y competencias organizadas por la FIFA y otros partidos y competencias que no estén bajo la jurisdicción de confederaciones o federaciones.\n"
                "2. También se aplica en casos de incumplimiento de objetivos estatutarios de la FIFA y otras normas, a menos que otro órgano tenga competencia.",
                ":orange[***Artículo 3 Ámbito de aplicación personal***:] \n\n Aplicable a :\n1. Federaciones\n", "\n2. Miembros de federaciones (incluyendo clubes)\n", "\n3. Oficiales \n", "\n4. Jugadores \n", "\n5. Oficiales de partido \n", "\n6. Agentes de fútbol con licencia FIFA \n", "\n7. Agentes organizadores de partidos con licencia FIFA \n", "\n8. Ligas independientes \n", "\n9. Personas elegidas o asignadas por FIFA para ejercer funciones",
                ":orange[***Artículo 4 Ámbito de aplicación temporal***:] \n\n- Aplica a infracciones cometidas después de su entrada en vigor.\n", "\n- También a infracciones anteriores si el código anterior tenía sanciones más leves.\n", "\n- Los órganos judiciales de la FIFA no anularán procedimientos ya iniciados.",
                ":orange[***Artículo 5 Derecho aplicable***:] \n\n Decisiones basadas en: \n", "\n- Estatutos y regulaciones de la FIFA\n", "\n- Reglas del juego\n", "\n- De forma subsidiaria, derecho suizo y otras normativas jurídicas",
                ":orange[***Artículo 6 Medidas disciplinarias***:] \n\n***- Medidas aplicables tanto a personas físicas como jurídcas:***","Adevertencia, apercibimiento, multas, devolución de premios, retirada de título, cumplimiento de obligaciones económicas","***- Medidas solo para personas físicas:***\n","Suspensiones, prohibiciones de acceso, prohibición de actividades futbolísticas, servicios comunitarios, retirada de licencias.\n","***-Medidas solo para personas jurídcas:***\n","Prohibiciones de inscripciones, partidos a puerta cerrada, limitaciones de espectadores, juego en terreno neutral, anulaciones, deducciones, descensos, exclusiones, repeticiones, implementación de planes de prevención, pérdidas de derechos, pagos de indemnizaciones.\n","***-Rango de multas:***\n","100 CHF a 1000000 CHF\n","***-Federaciones y clubes asumen solidariamente multas impuestas a jugadores y oficiales***\n","***-Las medidas pueden combinarse***\n", 
                ":orange[***Artículo 7 Directivas***:] \n\n - Las directivas indican una conducta específica que las personas deben seguir\n","- Los órganos judiciales de la FIFA pueden establecer directivas sobre cómo aplicar una sanción\n","- Pueden decretar indemnizaciones por daños si la responsabilidad recae en una federación o club.\n",
                ":orange[***Artículo 8 Responsabilidad***:] \n\n - Las infracciones cometidas intencionalmente o por negligencia serán sancionadas.\n","- Federaciones y clubes pueden ser responsables de la conducta de sus miembros, jugadores, oficiales, seguidores, etc., incluso sin culpa o negligencia.\n","- La tentativa es punible.\n","- Cualquiera que participe o induzca a cometer una infracción puede ser sancionado.\n",
                ":orange[***Artículo 9 Decisiones arbitrales***:] \n\n - Las decisiones del árbitro en el campo son definitivas y no revisables por la FIFA, a menos que haya un error claro.\n","- Las decisiones solo pueden revisarse en casos de confusión de identidad.\n","- Las protestas solo son admisibles si el error del árbitro fue confundir la identidad del jugador.\n","- En casos graves, se pueden tomar medidas disciplinarias incluso si el árbitro no vio la acción.\n","- Las decisiones arbitrales evidentemente incorrectas pueden ser objeto de protesta.\n",
                ":orange[***Artículo 10 Prescripción de las infracciones***:] \n\n -  Plazo de prescripción:\n","2 años para infracciones en partidos\n","10 años para infracciones antidopaje, transferencias de menores y manipulación de partidos.\n","5 años para otras infracciones\n","- El inicio del cómputo de prescripción varía según las circunstancias\n","- Las diligencias interrumpen los plazos de prescripción\n",
                ":orange[***Artículo 11 Deber de denunciar***:] \n\n - Las personas deben reportar inmediatamente cualquier violación del código\n","- Las denuncias infundadas o irresponsables pueden resultar en sanciones\n",
                ":orange[***Artículo 12 Obligación de colaborar***:] \n\n - Las partes deben actuar de buena fe durante el procedimiento\n","- Las personas sujetas al código deben de colaborar para esclarecer los hechos\n","- No colaborar puede resultar en sanciones\n","- Si las partes no colaboran, la decisión se basará en la información disponible\n",
                ":orange[***Artículo 13 Conducta ofensiva y violaciones de los principios del juego limpio***:] \n\n - Federaciones, clubes, jugadores, oficiales y otros deben respetar las Reglas de Juego y otros reglamentos de la FIFA, y mantener el juego limpio.\n","- Medidas disciplinarias pueden ser impuestas por violaciones específicas, como insultos, manifestaciones no deportivas, o modificar la edad de jugadores.\n",
                ":orange[***Artículo 14 Conducta incorrecta de los jugadores y los oficiales***:] \n\n - Establece diversas sanciones para jugadores y oficiales según la gravedad de su conducta (ejemplo: suspensión por juego brusco, actos violentos, conducta antideportiva hacia oficiales, etc.).\n","- Las infracciones cometidas incluso fuera del terreno de juego (como redes sociales) pueden ser sancionadas.\n","- Si un equipo se comporta inadecuadamente, puede ser sancionado.\n",
                ":orange[***Artículo 15 Discriminación***:] \n\n - Sanciones para quienes atenten contra la dignidad de personas o colectivos por diversos motivos (como raza, género, religión, etc.).\n","- Federaciones o clubes pueden ser sancionados si sus seguidores adoptan conductas discriminatorias.\n","- Las víctimas de discriminación pueden ser invitadas a declarar y tienen derechos específicos en el proceso.\n","- Suspensión definitiva de partidos por conducta racista/discriminatoria puede llevar a la derrota por renuncia.\n",
                ":orange[***Artículo 16. Partido no disputado y suspensión definitiva de un partido***:] \n\n- Sanciones para federaciones o clubes si un partido no se disputa o no se juega íntegramente por razones que no son de fuerza mayor.\n","- Federaciones o clubes pueden ser sancionados si sus seguidores adoptan conductas discriminatorias.\n","- Aclaraciones sobre amonestaciones en partidos suspendidos.\n",
                ":orange[***Artículo 17. Orden y seguridad en los partidos***:]\n",
                "- Las federaciones y clubes locales son responsables del orden y seguridad en y alrededor de los estadios.",
                "- Deben tomar medidas preventivas y garantizar la seguridad de los participantes y oficiales.",
                "- Las conductas inapropiadas de los seguidores, como invasiones de campo o lanzamiento de objetos, pueden llevar a sanciones, incluso si la organización no fue negligente."
                ":orange[***Artículo 18. Protestas***:]\n",
                "- Federaciones y clubes pueden presentar protestas.",
                "- Deben hacerlo en 24 horas post-partido y a través del portal jurídico de la FIFA.",
                "- Coste de presentación: 1000 CHF (devuelto si la protesta es admitida).",
                "- Razones válidas para protestas:",
                "Jugador no elegible.",
                "Terreno de juego impracticable.",
                "Error grave del árbitro.",
                ":orange[***Artículo 19. Alineación indebida***:]\n",
                "- Si un jugador no elegible participa, la FIFA puede imponer medidas disciplinarias.",
                "- El equipo del jugador inelegible será sancionado con derrota y multa mínima de 6000 CHF.",
                "- Acción de oficio por parte de la Comisión Disciplinaria.",
                ":orange[***Artículo 20. Manipulación de partidos o competiciones de fútbol***:]\n",
                "- Sanciones para quienes influencien ilícitamente o manipulen resultados o aspectos de partidos.",
                "- Multa mínima de 100 000 CHF y prohibición de actividades relacionadas con el fútbol (al menos 2 años).",
                "- Personas deben cooperar con la FIFA contra la manipulación; la falta de cooperación conlleva sanciones.",
                "- La Comisión Disciplinaria investiga y juzga casos de manipulación.",
                ":orange[***Artículo 21. Incumplimiento de decisiones***:]\n",
                "- Sanciones por no pagar cantidades debidas o no cumplir con decisiones de la FIFA o TAS.",
                "- Medidas incluyen multas, plazos de gracia, intereses, prohibiciones, deducciones, descensos, entre otros.",
                "- Procedimientos disciplinarios iniciados a petición del acreedor.",
                "- Federaciones y clubes responsables de ejecutar decisiones.",
                "- Sanciones por no respetar decisiones del TAS solo para procedimientos iniciados después del 15 de julio de 2019.",
                ":orange[***Artículo 22. Falsificación de documentos***:]\n",
                "- Sanciones para quienes creen, falsifiquen o usen documentos falsificados en actividades futbolísticas.",
                "- Multas y suspensiones de mínimo 6 partidos o 12 meses.",
                "- Federaciones o clubes pueden ser responsables por acciones de oficiales o jugadores.",
                ":orange[***Artículo 23. Procedimientos específicos***:]\n",
                "- Dopaje sancionado según Reglamento Antidopaje de la FIFA.",
                "- Infracciones relacionadas con Agentes de Fútbol, Agentes Organizadores de Partidos y la Cámara de Compensación sancionadas según reglamentos respectivos.",                                                                              
                ":orange[***Artículo 24. Ejecución de sanciones***:]\n",
                "- Plazo de prescripción para ejecutar sanciones: 5 años.",
                "- Comienza desde la entrada en vigor de la decisión firme.",
                ":orange[***Artículo 25. Determinación de las medidas disciplinarias***:]\n",
                "- Los órganos judiciales establecen medidas basándose en factores objetivos y subjetivos, considerando circunstancias atenuantes y agravantes.",
                "- Las medidas pueden limitarse geográficamente o a categorías específicas de juegos.",
                "- Se considerarán factores como cooperación del infractor y grado de culpa.",
                "- Al ejercer sus facultades discrecionales, el órgano judicial de la FIFA competente puede rebajar una medida disciplinaria o incluso prescindir de ella.",              
                ":orange[***Artículo 26. Reincidencia***:]\n",
                "- Se considera reincidencia cuando se comete una segunda infracción similar dentro de ciertos plazos.",
                "- La reincidencia es una circunstancia agravante.",
                "- Normas específicas para reincidencia en dopaje según el Código Antidopaje de la FIFA.",
                ":orange[***Artículo 27. Suspensión de la aplicación de medidas disciplinarias***:]\n",
                "- La aplicación de sanciones puede suspenderse.",
                "- Se establece un periodo de prueba para el sancionado, que varía entre 1 y 4 años.",
                "- Si se comete una nueva infracción durante este periodo, se revoca la suspensión y se aplica la sanción original, más una nueva.",
                "- Las medidas derivadas de manipulación de partidos no pueden suspenderse.",
                ":orange[***Artículo 28. Derrota por retirada o renuncia***:]\n",
                "- La sanción por retirada o renuncia implica un resultado de 3-0, 5-0 o 10-0, dependiendo de la modalidad de fútbol.",
                "- Si la diferencia de goles es mayor a favor del equipo contrario, se mantiene ese resultado.",
                "- Las amonestaciones del partido no se anulan, incluso si posteriormente se declara derrota por retirada o renuncia.",
                ":orange[***Artículo 29. Partidos a puerta cerrada***:]\n",
                "En partidos sin público, solo pueden asistir:",
                "- Hasta 200 personas de la federación o club visitante y 20 VIPs de cada federación.",
                "- 55 personas de cada equipo, incluyendo jugadores.",
                "- Personal de medios acreditados.",
                "- Policías y seguridad.",
                "- Personal relacionado con la infraestructura del estadio.",
                "- Máximo de 75 representantes de FIFA/confederación.",
                "- Personas con entradas de cortesía de FIFA/confederación.",
                "- Máximo de 1000 niños menores de 14 años de escuelas o academias de fútbol.",
                ":orange[***Artículo 30. Normas generales***:]\n",
                "- Los órganos judiciales de la FIFA tienen competencia en cuestiones disciplinarias.",
                "- Las confederaciones y federaciones son responsables en sus respectivas jurisdicciones.",
                "- La FIFA tiene jurisdicción en partidos y competencias que organiza y en otros escenarios específicos.",
                "- Las federaciones deben colaborar compartiendo documentos e información.",
                "- Las infracciones graves, como dopaje o manipulación de partidos, deben ser informadas a la FIFA.",
                "- La FIFA puede asumir la jurisdicción en ciertos casos si se considera necesario.",                                                             
                ":orange[***Artículo 31. Composición de los órganos judiciales de la FIFA***:]\n",
                "- Los órganos judiciales de la FIFA incluyen la Comisión Disciplinaria, la Comisión de Apelación y la Comisión de ética.",
                "- Están compuestos por un presidente, un vicepresidente y varios miembros.",
                "- Son elegidos por el Congreso por propuesta del Consejo durante cuatro años.",
                ":orange[***Artículo 32. Independencia e imparcialidad***:]\n",
                "- Los miembros deben ser independientes e imparciales.",
                "- Si existe conflicto de intereses, el miembro debe abstenerse.",
                "- Se pueden recusar miembros si hay dudas sobre su imparcialidad.",
                ":orange[***Artículo 33. Sesiones***:]\n",
                "- Las sesiones son convocadas por el presidente o el vicepresidente.",
                "- Puede haber sesiones con un solo juez.",
                "- El presidente, vicepresidente o juez único preside las sesiones.",
                ":orange[***Artículo 34. Confidencialidad***:]\n",
                "- Se debe mantener la confidencialidad en todos los procedimientos.",
                "- La FIFA puede hacer públicas ciertas decisiones.",
                "- La falta de confidencialidad puede ser sancionada.",
                ":orange[***Artículo 35. Secretaría***:]\n",
                "- La FIFA provee una secretaría para los órganos judiciales.",
                "- La secretaría se encarga del trabajo administrativo y gestión de expedientes.",
                "- También puede llevar a cabo investigaciones.",
                ":orange[***Artículo 36. Expertos en integridad***:]\n",
                "- Se puede nombrar a expertos para asistir en investigaciones.",
                "- Deben ser imparciales y cumplir con criterios de independencia.",
                ":orange[***Artículo 37. Exención de responsabilidad***:]\n",
                "Miembros y secretaría no son responsables salvo en casos de falta grave.",
                ":orange[***Artículo 38. Plazos***:]\n",
                "Define cómo se cuentan los plazos en procedimientos. Las festividades están incluidas en los plazos. No se pueden ampliar los plazos.",
                ":orange[***Artículo 39. Pruebas, apreciación de las pruebas y estándar probatorio***:]\n",
                "- Se pueden presentar cualquier tipo de pruebas.",
                "- El órgano judicial tiene discreción sobre la apreciación de las pruebas.",
                ":orange[***Artículo 40. Informes de los oficiales de partido***:]\n",
                "Se presume que los informes de los oficiales son exactos, pero se puede demostrar lo contrario.",
                ":orange[***Artículo 41. Carga de la prueba***:]\n",
                "- La FIFA lleva la carga de la prueba en infracciones disciplinarias.",
                "- Las partes deben proveer pruebas y hechos.",
                "- Las normas antidopaje tienen su propia regulación.",
                ":orange[***Artículo 42. Testigos***:]\n",
                "- Los testigos deben decir la verdad.",
                "- Las partes son responsables de los testigos que citen y deben cubrir sus costos y gastos.",
                ":orange[***Artículo 43. Participantes anónimos en el procedimiento***:]\n",
                "Si testificar pone en riesgo la integridad de alguien, el presidente o vicepresidente del órgano judicial tiene la autoridad para tomar medidas. Estas pueden incluir mantener la identidad del testigo en secreto, no hacer comparecer al testigo, distorsionar su voz, realizar interrogatorios fuera de la sala o por escrito, así como mantener información confidencial. Los testimonios no corroborados solo se usarán si cumplen ciertas condiciones. Revelar la identidad de alguien bajo anonimato está sujeto a sanciones.",
                ":orange[***Artículo 44. Identificación de participantes anónimos en el procedimiento***:]\n",
                "Los participantes anónimos serán identificados en privado, sin revelar su identidad a las partes. Estas recibirán una notificación breve que no contenga datos identificativos.",
                ":orange[***Artículo 45. Representación y asesoramiento legales***:]\n",
                "Las partes pueden tener representación legal incluso si su presencia no es requerida",
                ":orange[***Artículo 46. Asistencia jurídica gratuita***:]\n",
                "- Quienes carezcan de recursos pueden solicitar asistencia legal gratuita.",
                "- Es necesario presentar documentos que respalden la situación económica.",
                "- Se establecerá una lista de abogados dispuestos a trabajar pro bono.",
                "- El presidente de la Comisión Disciplinaria toma decisiones respecto a estas solicitudes.",
                ":orange[***Artículo 47. Idiomas de los procedimientos***:]\n",
                "- Los idiomas oficiales son español, francés e inglés.",
                "- Las decisiones se emitirán en estos idiomas.",
                "- Las federaciones se encargan de traducir si es necesario.",
                ":orange[***Artículo 48. Comunicación con las partes***:]\n",
                "- Las decisiones se notificarán a todas las partes.",
                "- La comunicación se efectúa mediante el portal jurídico de la FIFA.",
                "- Las partes deben mantener sus datos de contacto actualizados.",
                "- Las federaciones son responsables de comunicar las decisiones a los afectados.",
                ":orange[***Artículo 49. Costas y gastos***:]\n",
                "- La parte sancionada asumirá los costos y gastos, a menos que se indique lo contrario.",
                "- La FIFA cubre ciertos costos procesales.",
                "- Las partes se hacen cargo de sus propios gastos, con algunas excepciones.",
                ":orange[***Artículo 50. Efecto de las decisiones***:]\n",
                "- Las decisiones toman efecto una vez notificadas.",
                "- Algunas sanciones tienen efecto inmediato.",
                ":orange[***Artículo 51. Medidas provisionales***:]\n",
                "- El presidente o delegado del órgano judicial puede tomar medidas provisionales.",
                "- Estas medidas pueden ser impugnadas.",
                "- Tienen una duración inicial de hasta 90 días, con posibilidad de extensión en circunstancias excepcionales.",
                ":orange[***Artículo 52. Tribunal de Arbitraje Deportivo (TAS)***:]\n",
                "Las decisiones de la Comisión Disciplinaria y de Apelación pueden ser apeladas ante el TAS siguiendo los Estatutos de la FIFA.",
                ":orange[***Artículo 53. Comparecencia, derechos de las partes, audiencias, decisiones, comunicación y confidencialidad***:]\n",
                "- Normalmente no se requieren declaraciones orales; las decisiones se basan en expedientes.",
                "- Audiencias posibles si son solicitadas o consideradas necesarias.",
                "- Las partes pueden presentar su posición por escrito y examinar el expediente.",
                "- Las audiencias se graban y archivan, pero las partes generalmente no tienen acceso a las grabaciones.",
                ":orange[***Artículo 53. Comparecencia, derechos de las partes, audiencias, decisiones, comunicación y confidencialidad***:]\n",
                "- Las decisiones pueden tomarse aunque las partes estén ausentes.",
                "- Procedimientos múltiples contra una entidad pueden combinarse en una sola decisión.",
                "- Las audiencias no son públicas, salvo excepciones específicas.",
                "- Las partes pueden admitir su responsabilidad y solicitar una sanción específica.",
                "- Las comunicaciones con la FIFA se realizan principalmente a través del portal jurídico de la FIFA.",
                ":orange[***Artículo 54. Decisiones***:]\n",
                "- Las decisiones se toman por mayoría simple; en caso de empate, el presidente tiene el voto decisivo.",
                "- Las decisiones pueden ser tomadas en varios formatos, incluidas teleconferencias.",
                "- Las decisiones se notifican sin detalles completos, pero las partes pueden solicitar una decisión motivada.",
                ":orange[***Artículo 54. Decisiones***:]\n",
                "- Las decisiones motivadas incluyen un resumen, la infracción, consideraciones y criterios para sanciones.",
                "- Las decisiones en materia de dopaje incluyen fundamentación.",
                "- Las decisiones se publicarán, con posibles redacciones para proteger información confidencial.",
                ":orange[***Artículo 55. Inicio del procedimiento***:]\n",
                "- La secretaría de la Comisión Disciplinaria inicia procedimientos basados en varios informes, instancias y denuncias.",
                "- Cualquier persona puede informar conductas contrarias a la reglamentación de la FIFA.",
                ":orange[***Artículo 56. Jurisdicción***:]\n",
                "- La Comisión Disciplinaria tiene la autoridad para sancionar contravenciones que no están bajo la jurisdicción de otro órgano.",
                "- Detalla responsabilidades específicas de la Comisión Disciplinaria.",
                "- El presidente o vicepresidente pueden transferir casos a la Comisión de Apelación.",
                ":orange[***Artículo 57. Jurisdicción de los jueces únicos de la Comisión Disciplinaria***:]\n",
                "- El presidente puede decidir como juez único o delegar sus funciones.",
                "- Detalla las responsabilidades y facultades del juez único.",
                "- En ciertos casos, se puede proponer una sanción basada en el expediente existente.",
                ":orange[***Artículo 58. Propuesta de la secretaría***:]\n",
                "En casos específicos, la secretaría puede proponer sanciones basadas en el expediente existente.",
                ":orange[***Artículo 59. Clausura del procedimiento***:]\n",
                "Los procedimientos pueden cerrarse en casos de acuerdo, problemas financieros de una de las partes, desafiliación de un club o falta de pruebas de infracción.",
                ":orange[***Artículo 60. Jurisdicción de la Comisión de Apelación***:]\n",
                "- Resuelve recursos contra decisiones de la Comisión Disciplinaria y de la Comisión de Ética.",
                "- Plazos para anunciar y presentar recursos: 3 y 5 días respectivamente.",
                "- Tasa para recursos: 1000 CHF.",
                "- No cumplir plazos o requisitos resulta en inadmisibilidad del recurso.",
                ":orange[***Artículo 61. Admisibilidad de los recursos***:]\n",
                "- Decisiones de la Comisión Disciplinaria recurribles, excepto para ciertas medidas menores.",
                "- Solo decisiones motivadas pueden ser recurridas.",
                "- Si se combinan medidas, se admite recurso si al menos una supera límites mencionados.",
                ":orange[***Artículo 62. Legitimación para recurrir***:]\n",
                "- Personas que fueron parte en procedimientos anteriores pueden recurrir.",
                "- Federaciones y clubes pueden recurrir decisiones sobre sus jugadores, oficiales o miembros.",
                ":orange[***Artículo 63. Deliberaciones y decisiones***:]\n",
                "- La Comisión de Apelación opera a puerta cerrada.",
                "- Tiene competencia completa para revisar hechos y cuestiones jurídicas.",
                "- Las decisiones pueden confirmar, modificar o anular decisiones previas.",
                ":orange[***Artículo 64. Jurisdicción del presidente para actuar individualmente***:]\n",
                "El presidente tiene poderes específicos, incluyendo decidir sobre aspectos procesales, casos urgentes, recursos contra decisiones provisionales y ciertas sanciones.",
                ":orange[***Artículo 65. Efectos de los recursos***:]\n",
                "- Los recursos no suspenden efectos de decisiones, excepto pagos."
                "- El presidente puede decretar suspensión de la ejecución en ciertas circunstancias.",
                ":orange[***Artículo 66. Expulsión y suspensión por partidos***:]\n",
                "- Reglas específicas sobre comportamiento de jugadores y oficiales expulsados o suspendidos.",
                "- Efectos automáticos de expulsiones y reglas sobre cumplimiento de suspensiones.",
                ":orange[***Artículo 67. Traslado de amonestaciones***:]\n",
                "- Dos amonestaciones en diferentes partidos de una competición resultan en suspensión automática para el siguiente partido.",
                "- Las amonestaciones no se trasladan entre competencias, pero sí entre rondas de la misma competencia.",
                "- Los jugadores expulsados mantienen las amonestaciones del mismo partido.",
                ":orange[***Artículo 68. Anulación de amonestaciones***:]\n",
                "- La Comisión Disciplinaria puede anular amonestaciones a su discreción.",
                "- Solo puede realizarse una vez por competición.",
                ":orange[***Artículo 69. Traslado de suspensiones por partidos***:]\n",
                "- Las suspensiones se trasladan de una ronda a otra en la misma competición.",
                "- Las suspensiones impuestas por expulsión fuera de competición o no cumplidas en la competición se trasladan de varias maneras según el tipo de torneo o partido.",
                "- Si una selección es anfitriona de la fase final y no juega partidos clasificatorios, las suspensiones se trasladan al siguiente partido amistoso.",
                "- Las suspensiones por varias amonestaciones en una competición no aplican en otra.",
                "- Los oficiales cumplirán suspensiones con su club o federación.",
                "- Solo las personas sancionadas cumplirán las suspensiones trasladadas, incluso si cambian de función (de jugador a oficial o viceversa).",
                ":orange[***Artículo 70. Ampliación de las sanciones al ámbito mundial***:]\n",
                "- En infracciones graves, las entidades deben solicitar a la Comisión Disciplinaria la extensión mundial de sanciones.",
                "- La FIFA adoptará automáticamente sanciones de dopaje de otras federaciones o entidades.",
                "- Las solicitudes se deben presentar por escrito con evidencia.",
                "- Si no se solicita la ampliación, la Comisión Disciplinaria puede actuar de oficio.",
                "- Se aprueban las ampliaciones si cumplen ciertas condiciones.",
                "- La sanción ampliada tiene efecto en todas las federaciones y confederaciones.",
                ":orange[***Artículo 71. Revisión***:]\n",
                "- Se puede solicitar revisión si se descubren hechos o pruebas que podrían haber llevado a una decisión más favorable.",
                "- La solicitud debe presentarse en un plazo de 10 días tras descubrir los motivos.",
                "- El plazo de prescripción es de un año.",
                ":orange[***Artículo 72. Idiomas oficiales***:]\n",
                "- El código se publica en español, francés e inglés.",
                "- En caso de discrepancia, prevalece la versión en inglés.",
                ":orange[***Artículo 73. Género y número***:]\n",
                "- Los términos aplican a ambos géneros.",
                "- El singular incluye el plural y viceversa.",
                ":orange[***Artículo 74. Normas disciplinarias específicas***:]\n",
                "- Pueden aplicarse normas específicas en fases finales de competencias de la FIFA.",
                "- Las federaciones o clubes deben ser informados antes del primer partido.",
                ":orange[***Artículo 75. Códigos disciplinarios de las federaciones***:]\n",
                "- Las federaciones deben adaptar sus códigos disciplinarios a este código.",
                "- Las federaciones deben enviar a la FIFA una copia de su reglamentación.",
                "- Las federaciones deben asegurarse de que las personas con antecedentes penales no formen parte de la dirección.",
                ":orange[***Artículo 76. Adopción y entrada en vigor***:]\n",
                "- Adoptado el 16 de diciembre de 2022 en Doha.",
                "- Entrada en vigor el 1 de febrero de 2023.",
                ":orange[***ANEXO 1. Lista de medidas disciplinarias***:]\n",
                "El artículo 6 del código detalla las medidas disciplinarias que la FIFA puede imponer a individuos y entidades. Aunque este anexo ofrece una lista específica de dichas medidas, no es una lista completa ni obligatoria. Las decisiones se toman según cada caso, basándose en los detalles de la infracción y considerando tanto factores agravantes como atenuantes, sin contradecir los principios generales del artículo 25.",
                "1 También podrá decretarse la deducción de puntos y el descenso de categoría, además de la prohibición de inscribir jugadores, en caso de que persista el impago, de reincidencia o de infracciones graves, o de no haber sido posible ejecutar o cumplir, por algún motivo, el pago o la decisión en su totalidad.",
                "2 Se podrán imponer más medidas disciplinarias.",
                "3 Esta multa se impondría además de las multas particulares cuando el árbitro imponga sanciones disciplinarias personales a cinco o más jugadores del equipo en el partido correspondiente.",
                



                

                                               
            ]
        },
        {
            "titulo": ":blue_book: Codigo de Etica",
            "resumen": [
                "Texto resumen Codigo de Etica..."
            ]
        },
        {
            "titulo": ":notebook_with_decorative_cover: Reglamento sobre el Estatuto y la Transferencia de jugadores",
            "resumen": [
                ":orange[***Artículo 7***:] La asociación que inscribe a un jugador debe entregar un pasaporte del jugador con todos los datos relevantes del jugador, que incluirá los clubes en los que ha estado inscrito desde el año en que cumplió 12 años.",
                ":orange[***Artículo 7***:] Para los derechos relacionados con las compensaciones por formación que están sujetos al Reglamento de la Cámara de Compensación de la FIFA, se generará un Pasaporte Electrónico del Jugador (EPP) que contiene información consolidada sobre la inscripción del jugador a lo largo de su carrera.",
                ":orange[***Artículo 8***:] La solicitud de inscripción debe presentarse con una copia del contrato del jugador profesional. El órgano competente puede considerar cualquier enmienda en el contrato o acuerdos adicionales que no se hayan presentado debidamente.",
                ":orange[***Artículo 9***:] Los jugadores solo pueden inscribirse en una nueva asociación cuando esta haya recibido el CTI de la asociación anterior, expedido gratuitamente y sin condiciones.",
                ":orange[***Artículo 9***:] Las asociaciones no pueden solicitar la expedición de un CTI para permitir a los jugadores participar en partidos amistosos en el contexto de una prueba.",
                ":orange[***Artículo 9***:] La nueva asociación debe informar por escrito a la asociación o asociaciones del club o clubes que formaron y educaron al jugador entre los 12 y los 23 años de edad sobre la inscripción del jugador como profesional una vez recibido el CTI.",
                ":orange[***Artículo 9***:] Los jugadores menores de 10 años no necesitan el CTI.",
                ":orange[***Artículo 10***:] Un club puede ceder en préstamo a un profesional a otro club basándose en un acuerdo por escrito. Durante el periodo de préstamo, las obligaciones contractuales entre el profesional y su club original quedan suspendidas, excepto si se especifica lo contrario por escrito.",
                ":orange[***Artículo 10***:] El contrato de préstamo puede prolongarse con el consentimiento por escrito del profesional",
                ":orange[***Artículo 10***:] Se prohíbe al nuevo club llevar a cabo un subpréstamo o transferencia permanente de un profesional a un tercer club",
                ":orange[***Artículo 10***:] Si el contrato entre el profesional y el nuevo club se rescinde unilateralmente antes de que concluya la duración acordada en el contrato de préstamo, el profesional tiene derecho a volver al club anterior.",
                ":orange[***Artículo 10***:] A partir del 1 de julio de 2024, se limitará el número de préstamos: un club podrá ceder en préstamo un máximo de seis profesionales y tener en plantilla un máximo de seis profesionales cedidos en préstamo.",
                ":orange[***Artículo 10***:] Existen excepciones para estos límites, por ejemplo, si el préstamo ocurre antes de que el profesional cumpla 21 años o si el profesional fue formado por el club original.",
                ":orange[***Artículo 10***:] Hay restricciones independientes de la edad del jugador o de si ha sido formado por el club: un club puede ceder en préstamo a un club específico un máximo de tres profesionales y tener en plantilla un máximo de tres profesionales cedidos en préstamo por un club específico.",
                ":orange[***Artículo 10***:] Existen periodos de transición para estas limitaciones",
                ":orange[***Artículo 16***:] Los contratos no pueden rescindirse de forma unilateral durante un periodo de competición.",
                ":orange[***Artículo 17***:] Las consecuencias de la ruptura de contratos sin justificación son: a. La parte que rompe el contrato tiene que pagar una indemnización, calculada de acuerdo con la legislación nacional, las características del deporte y otros criterios objetivos. b. Si un jugador no ha firmado un nuevo contrato después de la rescisión de su contrato anterior, la indemnización generalmente equivaldrá al valor residual del contrato que se ha rescindido prematuramente.",
                ":orange[***Artículo 17***:] Las consecuencias de la ruptura de contratos sin justificación son: c. En caso de que el jugador haya firmado un nuevo contrato antes de la decisión, el valor del nuevo contrato durante el periodo correspondiente al tiempo restante del contrato rescindido se deducirá del valor residual del contrato rescindido. d. Los acuerdos colectivos válidamente negociados pueden divergir de estos principios. e. El derecho a una indemnización no puede cederse a terceros.",
                ":orange[***Artículo 17***:] Las consecuencias de la ruptura de contratos sin justificación son: f. Si un jugador debe pagar una indemnización, él y su nuevo club son conjuntamente responsables de hacerlo. g. Se impondrán sanciones deportivas a un jugador que rompa un contrato durante un periodo protegido. h. Se impondrán sanciones deportivas a un club que rompa un contrato durante un periodo protegido, o que haya inducido a romper un contrato.",
                ":orange[***Artículo 18***:] Las disposiciones especiales relacionadas con los contratos entre jugadores profesionales y clubes son: a. Los contratos deben incluir el nombre del agente, su cliente, su número de licencia de la FIFA y su firma. b. La duración mínima de un contrato será desde la fecha de inscripción hasta el final de la temporada; la duración máxima será de cinco años. Los jugadores menores de 18 años no pueden firmar un contrato de una duración mayor de tres años.",
                ":orange[***Artículo 18***:] Las disposiciones especiales relacionadas con los contratos entre jugadores profesionales y clubes son: c. Un club que quiera firmar un contrato con un jugador profesional debe comunicar su intención por escrito al club del jugador antes de iniciar las negociaciones. d. La validez de un contrato no puede depender de los resultados de un examen médico o de la obtención de un permiso de trabajo. e. Si un jugador profesional firma más de un contrato para el mismo periodo, se aplicarán las disposiciones del capítulo IV.",
                ":orange[***Artículo 18***:] Las disposiciones especiales relacionadas con los contratos entre jugadores profesionales y clubes son: f. Las cláusulas contractuales que permiten al club un periodo adicional para pagar al jugador no serán reconocidas. g. Las jugadoras tienen derecho a disfrutar de la baja por maternidad durante el periodo de vigencia de su contrato, percibiendo dos terceras partes del salario estipulado en el contrato."
            ]
        },
        {
            "titulo": ":notebook: Reglamento de procedimiento del Tribunal del Fútbol",
            "resumen": [


            ]
        },
        {
            "titulo": ":green_book: Reglamento de la Cámara de Compensación",
            "resumen": [
                ":green[***Artículo 1: Objetivos***:] \n1. ***Obligación estatutaria de la FIFA de regular las transferencias de fútbol.***",
                "2. ***Objetivos fundamentales:***",
                "- Proteger la estabilidad contractual entre jugadores y clubes.",
                "- Incentivar la formación de jugadores jóvenes.",
                "- Fomentar la solidaridad en el fútbol.",
                "- Proteger a los menores.",
                "- Conservar el equilibrio competitivo.",
                "- Garantizar regularidad en competencias deportivas.",
                "3. ***Objetivos específicos de la Cámara:***",
                "- Tramitar pagos de transferencias entre clubes.",
                "- Proteger y promover transparencia en transferencias.",
                "- Impedir conductas fraudulentas en transferencias.",
                "4. ***Actúa como intermediaria para compensaciones por formación.***",
                ":green[***Artículo 2: Ámbito de aplicación***:] \n-  Define el proceso de pagos a través de la Cámara de Compensación de la FIFA.",
                "-  Aplica solamente al fútbol de once jugadores.",
                "-  Aplicable a todas las partes sujetas a los Estatutos de la FIFA.",
                ":green[***Artículo 3: Cámara de Compensación de la FIFA***:] \n- La Cámara es una entidad independiente de FIFA para intermediar en pagos de transferencias.",
                "- No busca beneficio financiero de los activos o transacciones.",
                "- Las relaciones jurídicas se rigen por los términos de la Cámara y este reglamento.",
                "- Se aplica el Reglamento sobre la Protección de Datos de la FIFA",
                ":green[***Artículo 4: Registro y transferencia de jugadores***:] \n- Federaciones y clubes deben proporcionar información electrónica fiable sobre inscripciones y transferencias.",
                "- Deben utilizar sistemas electrónicos específicos para enviar información a FIFA.",
                "- Obligaciones sobre cómo y dónde se registran los jugadores.",
                "- Responsabilidad sobre la precisión y actualización de los datos.",
                "- Categorización de clubes según criterios específicos.",
                "- Solo se considerarán jugadores inscritos por una federación miembro con FIFA ID para compensaciones automáticas.",
                ":green[***Artículo 5: Factor desencadenante de compensaciones por formación: primera inscripción como profesional***:]", "***Primera inscripción en última federación como aficionado:***",
                "- Deben introducir o confirmar la primera inscripción del jugador como profesional en el sistema.",
                "- Trasferencias entre clubes de la misma federación deben ser registradas.",
                "- La FIFA recibe datos de la primera inscripción profesional en 30 días.",
                "***Primera inscripción en última federación como aficionado: declaración manual:***",
                "- Si no hay integración con el sistema, la federación debe declarar la inscripción manualmente.",
                "- Se necesita aprobación de la FIFA para declaraciones manuales.",
                "- Deben proporcionar datos específicos y subir contrato de trabajo.",
                "- FIFA puede requerir más documentos en cualquier momento.",
                "***Primera inscripción en una federación diferente:***",
                "- Se registra en el TMS como transferencia internacional.",
                "- El TMS detectará esta inscripción como un factor desencadenante para compensaciones por formación.",
                ":green[***Artículo 6: Factor desencadenante de compensaciones por formación: transferencia internacional***:] \n- Introducción de todos los datos de transferencia internacional en el TMS conforme al anexo 3 del RETJ.",
                "- Las compensaciones por formación no se incluyen en la cantidad declarada como indemnización por transferencia.",
                "- El TMS identificará transferencias internacionales con derecho a compensaciones por formación",
                ":green[***Artículo 7: Factor desencadenante de compensaciones por formación: transferencia nacional con indemnización***:] \n- Transferencias nacionales registradas en un sistema electrónico de transferencias.",
                "- Las federaciones deben garantizar la veracidad de los datos y documentos presentados por clubes afiliados.",
                "- Información sobre transferencias y comprobantes de pago se envían a la FIFA en un plazo de 30 días.",
                "- El TMS identificará transferencias nacionales con indemnización que puedan generar compensaciones por formación.",
                "- En caso de fallas en el sistema electrónico, se permite una declaración manual en el TMS con ciertas condiciones y aprobación de la FIFA.",
                "- Existe una excepción para federaciones con más de 100 transferencias nacionales con indemnización en el año anterior.",
                ":green[***Artículo 8: Pasaporte deportivo electrónico (EPP)***:] \n- Al detectarse un factor para compensación por formación, el TMS generará un EPP provisional para el jugador.",
                "- Federaciones y clubes tienen 10 días para revisar los EPP provisionales."
                "- Durante el periodo de inspección, clubes y federaciones pueden solicitar inclusiones en el EPP definitivo si no figuran en el provisional.",
                "- La Secretaría General de la FIFA revisará el EPP provisional para verificar exactitud, pudiendo descartarlo o reabrirlo bajo circunstancias justificadas.",
                ":green[***Artículo 9: Proceso de revisión del EPP***:] \n- Inicio del proceso de revisión del EPP en el TMS por la Secretaría General de la FIFA tras una inspección.",
                "- Invitación a varias partes, incluidas federaciones miembro, clubes afiliados, y otros entes relevantes a participar en el proceso.",
                "- El proceso tiene una duración estándar de 10 días, pero puede extenderse en situaciones excepcionales.",
                "- Las federaciones miembro pueden revisar y solicitar modificaciones de los datos",
                "- Para modificar datos, deben presentarse documentos justificativos como la inscripción del jugador, certificados de transferencia y contratos de trabajo.",
                "- Los clubes deben presentar documentación relacionada con ofertas de contrato a jugadores y posibles indemnizaciones por formación.",
                "- Los clubes formadores pueden renunciar a sus derechos de compensación o disputar la validez de una renuncia.",
                "- La Secretaría General puede pedir información adicional y comunicará la finalización del proceso a todas las partes.",
                ":green[***Artículo 10: Decisión de la FIFA***:] \n- La Secretaría General evalúa las solicitudes de modificación post-revisión.",
                "- Si una solicitud es ambigua o incompleta, se otorgan 5 días adicionales para aportar información.",
                "- Las partes pueden ser consultadas sobre el derecho de un club a recibir compensaciones por formación.",
                "- La Secretaría General decide qué datos se incluirán en el EPP final. Si hay complejidades, la Cámara de Resolución de Disputas interviene.",
                "- El TMS calcula automáticamente la distribución de compensaciones basado en el EPP definitivo.",
                "- El EPP definitivo y la orden de asignación se notificarán a todos los participantes.",
                "- Si no se presenta un recurso a tiempo, el EPP y la orden de asignación son definitivos y vinculantes.",
                ":green[***Artículo 11: Comprobante de pago de la indemnización por transferencia***:] \n- Para transferencias internacionales con indemnización, el nuevo club debe subir el comprobante de pago al TMS en 30 días.",
                "- Para transferencias nacionales con indemnización, el comprobante se carga en el sistema electrónico de transferencias nacionales, validado por la federación miembro y luego transmitido a la FIFA.",
                "- Si la transferencia nacional se declara manualmente, la federación miembro carga el comprobante en el TMS en 30 días.",
                "- Para el cálculo de la orden de asignación, se considera el monto del comprobante de pago, incluida una retención del 5% por contribución de solidaridad",
                
                
                
            ]
        },
        {
            "titulo": ":ledger: Reglamento sobre Agente Fifa",
            "resumen": [
                ":orange[***Importante***:]",
                "- No se puede cobrar comision de por transferencia de jugadores a futuro cuando hemos gestionado un contrato.",
                "- Los agentes de fútbol solo pueden representar a un cliente si han firmado un contrato de representación con ese cliente.",
                "- Solo los agentes de fútbol pueden contactar a un posible cliente para servicios de representación.",
                "- Los contratos de representación entre un agente de fútbol y una persona no pueden exceder los dos años y deben renovarse a través de un nuevo contrato de representación. No se permiten cláusulas de renovación automática.",
                "- Los agentes de fútbol solo pueden tener un contrato de representación vigente con la misma persona a la vez. Deben informar al cliente sobre la necesidad de asesoría jurídica independiente y obtener confirmación por escrito de que el cliente ha obtenido o renunciado a dicha asesoría.",
                "- No existe un límite en la duración de los contratos de representación entre una entidad de origen o de destino y un agente de fútbol.",
                "- Los agentes de fútbol pueden firmar varios contratos de representación con la misma entidad de origen o de destino.",
                "- Un contrato de representación es válido solo si incluye detalles como la identidad de las partes, la duración, los honorarios del agente, la naturaleza de los servicios y las firmas de todas las partes.",
                "- Los agentes de fútbol solo pueden representar a una parte en una transacción, a menos que ambas partes consientan explícitamente la doble representación.",
                "- Los agentes de fútbol no pueden representar a más de una parte en una misma transacción, con una única excepción...",
                "- Un agente de fútbol y un agente vinculado no pueden representar a clientes diferentes en una misma transacción.",
                "- Todos los acuerdos de transferencia y contratos laborales deben especificar el nombre del agente de fútbol, su número de licencia de la FIFA, su firma y el nombre de su cliente.",
                "- Los clientes pueden negociar y formalizar transacciones sin la mediación de un agente de fútbol.",
                "- No se permiten cláusulas que limiten o penalicen a una persona por negociar o formalizar un contrato laboral sin un agente de fútbol.",
                "- Ambas partes pueden rescindir un contrato de representación en cualquier momento si hay una causa justificada. Si una parte rescinde un contrato sin causa justificada, debe compensar a la otra parte por cualquier daño resultante. Se considera causa justificada si ocurren ciertas circunstancias que hacen que sea inaceptable esperar que una de las partes mantenga la relación contractual.",
                ":green[***Art.12***:] Establece las normas para los contratos de representación. Los contratos deben ser firmados antes de que un agente pueda representar a un cliente y no pueden exceder los dos años de duración si el cliente es una persona. Los agentes solo pueden representar a una persona a la vez, a menos que haya consentimiento explícito para la doble representación en una transacción. Todos los contratos deben incluir detalles específicos, y se permite que los clientes negocien transacciones sin un agente. Cualquier parte puede rescindir el contrato con causa justificada, y si se rescinde sin causa, se debe compensar a la otra parte.",
                ":blue[***Art.18***:] Los clientes que deciden no actuar en su propio nombre sólo pueden contratar a un agente de fútbol para la prestación de servicios de representación.",
                ":blue[***Art.18***:] Los clientes deben pagar los honorarios acordados con el agente de fútbol en los plazos establecidos en el reglamento y el contrato de representación.",
                ":blue[***Art.18***:] Los clientes deben verificar que el agente de fútbol tenga la licencia correspondiente de la FIFA antes de firmar el contrato de representación.",
                ":blue[***Art.18***:] Los clientes deben colaborar con la federación miembro, confederación y/o FIFA correspondiente en cualquier solicitud relacionada con el agente de fútbol.",
                ":blue[***Art.18***:] Los clientes tienen derecho a solicitar al agente de fútbol un calendario detallado de todos los pagos realizados (incluidos honorarios, gastos y otras remuneraciones).",
                ":blue[***Art.18***:] Los clientes, en caso de ser clubes, deben subir la información requerida al sistema de correlación de transferencias de la FIFA (TMS) en un plazo de catorce días después de su ocurrencia. Esto incluye la información requerida después de cada transferencia internacional, modificaciones del contrato de representación, contratos no relacionados con la representación y pagos de honorarios.",
                ":blue[***Art.18***:] Los clientes deben informar inmediatamente a la FIFA, las confederaciones o las federaciones miembro de cualquier incumplimiento de este reglamento.",
                ":blue[***Art.18***:] Los clientes y sus oficiales no pueden contratar a una persona sin licencia para la prestación de servicios de representación, ni aceptar o solicitar un beneficio indebido de un agente de fútbol.",
                ":blue[***Art.18***:] Los clientes no pueden ofrecer ninguna retribución a un agente de fútbol más allá de los honorarios acordados, interferir en la libre elección de una persona para seleccionar al agente que la representará, ni asistir en ninguna evasión de los límites de los honorarios establecidos en este reglamento.",
                ":blue[***Art.18***:] Los clientes no pueden tener intereses en una agencia o en la actividad de un agente de fútbol.",
                ":blue[***Art.18***:] Las federaciones miembro, clubes y ligas independientes no pueden inducir o coaccionar a una persona para que incumpla los términos del contrato de representación con su agente de fútbol.",
                ":blue[***Art.18***:] Los clientes no pueden permitir que un agente de fútbol o su agencia tengan interés en ellos, y deben informar inmediatamente a la FIFA de cualquier incumplimiento de este reglamento”",
                ":red[***Art.19***:] La FIFA publicará los nombres e información de todos los agentes de fútbol.",
                ":red[***Art.19***:] La FIFA divulgará los clientes que cada agente de fútbol representa, así como la vigencia y si su contrato de representación es exclusivo o no.",
                ":red[***Art.19***:] La FIFA publicará los servicios de representación que los agentes de fútbol prestan a cada cliente.",
                ":red[***Art.19***:] La FIFA revelará cualquier sanción impuesta a un agente de fútbol o a un cliente.",
                ":red[***Art.19***:] La FIFA publicará los datos de todas las transacciones en las que participan los agentes de fútbol, incluyendo los honorarios que perciben.",
                ":grey[***Art.20***:] La Cámara de Agentes del Tribunal del Fútbol tiene la jurisdicción para resolver disputas que surjan de, o estén relacionadas con, un acuerdo de representación de alcance internacional, siempre que la reclamación se realice de acuerdo con el Reglamento de Procedimiento del Tribunal del Fútbol y no hayan transcurrido más de dos años desde el hecho que provocó la disputa.",
                ":grey[***Art.20***:] Los procedimientos específicos para la resolución de disputas se detallan en el Reglamento de Procedimiento del Tribunal del Fútbol.",
                ":grey[***Art.20***:] En caso de disputas surgidas de, o relacionadas con, un contrato de representación de dimensión nacional, el órgano decisorio establecido en el reglamento nacional sobre agentes de fútbol de la federación miembro relevante tendrá la jurisdicción para resolver dichas disputas.",
                ":grey[***Art.20***:] Esto no limita el derecho de cualquier agente de fútbol o cliente a llevar un caso ante un tribunal ordinario.",
                ":violet[***Art.21***:] La Comisión Disciplinaria de la FIFA y, cuando corresponda, la Comisión de Ética independiente, tienen competencia para imponer sanciones a cualquier agente de fútbol o cliente que incumpla este reglamento, los Estatutos de la FIFA o cualquier otro reglamento de la FIFA. Tienen jurisdicción sobre toda conducta vinculada a un contrato de representación de dimensión internacional o a un traspaso internacional o una transacción internacional.",
                ":violet[***Art.21***:] La federación miembro correspondiente es responsable de ejecutar las sanciones impuestas a aquellos agentes de fútbol o clientes que incumplan el reglamento nacional sobre agentes de fútbol. Tienen jurisdicción sobre toda conducta vinculada a un contrato de representación de dimensión nacional o a un traspaso nacional o una transacción nacional.",
                ":green[***Art.22***:] Los contratos de representación que venzan el 1 de octubre de 2023 o después de la fecha en la que sea aprobado el reglamento seguirán vigentes hasta su fecha natural de vencimiento, independientemente de si cumplen o no los requisitos mínimos establecidos en el artículo 12, apartado 7.",
                ":green[***Art.22***:] Los nuevos contratos de representación o aquellos que se renueven después de la aprobación de este reglamento deberán cumplir con las disposiciones del mismo a partir del 1 de octubre de 2023.",
                ":green[***Art.22***:] Cualquier persona que haya formalizado un contrato de representación bajo estas características estará obligada a obtener una licencia de acuerdo con el presente reglamento para poder seguir prestando servicios de representación a partir del 1 de octubre de 2023.",
                ":orange[***Art.23***:] Trata sobre: Agentes en posesión de una licencia en virtud de una versión anterior del reglamento sobre los agentes de jugadores de la FIFA",
                ":orange[***Art.23***:] Las personas que posean una licencia de agente según versiones anteriores del Reglamento sobre los Agentes de Jugadores de la FIFA (1991, 1995, 2001 o 2008) estarán exentas de aprobar el examen actual si cumplen con varias condiciones: Enviar una solicitud para la nueva licencia de acuerdo con este reglamento antes del 30 de septiembre de 2023. Demostrar que poseen una licencia de agente bajo las versiones anteriores del reglamento. Cumplir con los requisitos de elegibilidad relevantes en el momento de la solicitud. Acreditar su registro como intermediario, o como propietario, director o empleado de una persona jurídica registrada como intermediario, en una federación entre el 1 de abril de 2015 y la fecha de aprobación de este reglamento. Cumplir con lo estipulado en el artículo 7 de este reglamento, después de recibir la confirmación de la FIFA de que están exentos de presentar el examen.",
                ":orange[***Art.23***:] Si un agente con licencia previa cumple con las condiciones, se le otorgará la licencia de acuerdo con el artículo 8 de este reglamento. Luego estarán sujetos a los requisitos de licencia continua, incluyendo la obtención de un número determinado de créditos de desarrollo profesional continuo cada año durante cinco años.",
                ":orange[***Art.23***:] La Secretaría General de la FIFA es responsable de verificar el cumplimiento de los requisitos mencionados en el primer punto.",
                ":blue[***Art.24***:] Trata sobre: Reconocimiento de los sistemas de licencias nacionales",
                ":blue[***Art.24***:] La FIFA puede reconocer un sistema nacional de licencias para agentes deportivos que permita la prestación de servicios equivalentes a los servicios de representación en un país o territorio, siempre que se establezcan los requisitos de elegibilidad para los solicitantes y licenciatarios, y un requisito para que los solicitantes aprueben un examen que incluya preguntas relacionadas con los reglamentos de fútbol vigentes u otros requisitos formativos relevantes.",
                ":blue[***Art.24***:] La federación miembro del país o territorio en el que se aplicará el sistema deberá enviar a la Secretaría General de la FIFA las solicitudes de reconocimiento de sistemas de licencias de agentes deportivos establecidos de acuerdo con la legislación nacional.",
                ":blue[***Art.24***:] Cualquier titular de una licencia que acredite para prestar servicios equivalentes a los servicios de representación en un país o territorio específico quedará exento del requisito de aprobar el examen establecido en este reglamento, siempre que se cumplan ciertas condiciones, incluyendo que la federación miembro haya recibido reconocimiento por parte de la FIFA y que la persona cumpla con los requisitos de elegibilidad.",
                ":blue[***Art.24***:] Si un solicitante cumple con las condiciones correspondientes, se le otorgará la licencia de acuerdo con el artículo 8 de este reglamento. A partir de ese momento, estará sujeto a los requisitos continuos de licencia estipulados en este reglamento, incluyendo la obtención de un número determinado de créditos de desarrollo profesional continuo cada año durante cinco años.",
                ":blue[***Art.24***:] La Secretaría General de la FIFA es responsable de tomar decisiones sobre cualquier solicitud realizada en virtud de este artículo.",
                ":green[***Art.25***:] Trata sobre: Grupo de trabajo sobre los agentes de fútbol",
                ":green[***Art.25***:] La FIFA establecerá un grupo de trabajo específico compuesto por representantes de las partes interesadas del fútbol profesional y organizaciones de agentes.",
                ":green[***Art.25***:] Este grupo de trabajo actuará como un órgano consultivo permanente en cuestiones relacionadas con los agentes de fútbol.",
                ":grey[***Art.26***:] Trata sobre: Casos no previstos",
                ":grey[***Art.26***:] La Secretaría General de la FIFA tomará decisiones sobre cualquier asunto no cubierto por este reglamento.",
                ":grey[***Art.26***:] Los casos de fuerza mayor que afecten a este reglamento serán resueltos por el Consejo de la FIFA y sus decisiones serán definitivas.",
                ":red[***Art.27***:] Trata sobre: Idiomas oficiales",
                ":red[***Art.27***:] En caso de discrepancias en la interpretación de los textos en los diferentes idiomas de este reglamento, la versión en inglés será la que prevalezca.",
                ":orange[***Art.28***:] Trata sobre: Entrada en vigor",
                ":orange[***Art.28***:] Este reglamento fue aprobado por el Consejo de la FIFA en su sesión del 16 de diciembre de 2022, y entró en vigor de la siguiente manera: a) El 9 de enero de 2023: Los artículos 1 a 10 y 22 a 27, que se relacionan en general con el procedimiento para obtener la licencia. b) El 1 de octubre de 2023: El resto de los artículos, que se relacionan en general con la actividad de los agentes de fútbol, así como con las obligaciones de los agentes de fútbol y los clientes. Especifica que la obligación de los clientes de solo contratar a un agente de fútbol para la prestación de servicios de representación será efectiva para todas las transacciones a partir del 1 de octubre de 2023.",
                ":orange[***Art.28***:] El Reglamento de la FIFA sobre las Relaciones con Intermediarios quedó revocado a partir del 1 de octubre de 2023."
            ]
        },
        {
            "titulo": ":books: Herramientas de Salvaguardia de la infancia del programa FIFA Guardians",
            "resumen": [
                ":blue[***Salvaguardia***:] \n\nLas medidas que se adoptan para garantizar que todos los niños estén a salvo de cualquier daño cuando practican el fútbol. Significa hacer todo lo posible de manera proactiva para minimizar el riesgo y prevenir el maltrato infantil.", 
                ":blue[***Como parte de nuestra política, adoptaremos las siguientes medidas:***:]",
                "- Nombrar un oficial de salvaguardia.",
                "- Establecer un grupo directivo interno que guíe nuestro trabajo y/o un grupo consultivo externo de expertos.",
                "- Planificar, identificar y establecer colaboraciones con las autoridades/ agencias locales de protección infantil y organizaciones de la sociedad civil que tengan experiencia en esta área y que puedan proporcionar ayuda y asesoramiento.",
                "- Garantizar la adopción de medidas adecuadas e inmediatas para hacer frente a las denuncias de maltrato, mediante la remisión de las cuestiones planteadas a las autoridades oficiales pertinentes",
                "- Desarrollar un plan de implantación/acción para promover y establecer medidas de salvaguardia en toda la FM",
                "- Prevenir la contratación/asignación de personas inadecuadas (personal y voluntarios) en el fútbol mediante procedimientos seguros de contratación y preselección",
                "- Asegurarse de que todas las personas comprendan sus funciones y responsabilidades con respecto a la salvaguardia en el fútbol, y proporcionar a todo el personal y a los voluntarios la formación adecuada cuando se incorporen a la organización, así como proporcionar formación continua y actualizaciones con regularidad (al menos una vez al año).",
                "- Exigir a todos los miembros del personal y a los voluntarios que firmen y cumplan el código de conducta.",
                "- Gestionar las cuestiones relacionadas con malas prácticas e incumplimientos del código de conducta a través del órgano competente pertinente de la FM",
                "- Gestionar las cuestiones relacionadas con malas prácticas e incumplimientos del código de conducta a través del órgano competente pertinente de la FM",
                "- Asegurarse de que los niños estén informados de sus derechos y comprendan adónde ir si tienen cualquier inquietud o necesitan ayuda",
                "- Garantizar que existan procedimientos de investigación, disciplinarios y de recurso para gestionar adecuadamente las denuncias, los informes y los casos en los que se haya determinado que el personal o los voluntarios han infringido esta política y el código de conducta. Las autoridades competentes se encargarán de la gestión de los casos y del apoyo a las víctimas de malos tratos (o presuntas víctimas), así como de los acusados. Cualquier investigación interna de la FM se suspenderá hasta que se completen las investigaciones oficiales, a fin de que los procesos internos no pongan en peligro las pesquisas legales o penales.",
                "- Garantizar que los registros confidenciales y exactos de las cuestiones planteadas, denuncias e informes y las pruebas presentadas se conserven y almacenen de forma segura.",
                "- Asegurarnos de evaluar continuamente la forma en que los niños participan en el fútbol en nuestro país y de revisar nuestras prácticas de salvaguardia con regularidad (al menos una vez al año) al objeto de garantizar que aprendemos sobre la salvaguardia y la mejoramos, siguiendo la evolución de las mejores prácticas y la legislación nacional. Además, nos aseguraremos de consultar proactivamente con los niños en colaboración con las agencias y los socios locales.",
            ]
        }
    ]

    for seccion in secciones:
        with st.expander(seccion["titulo"]):  # Expander con el título de la sección
            for resumen in seccion["resumen"]:
                st.markdown(resumen)  # Mostrar el resumen con formato



if __name__ == "__main__":
    mostrar_resumenes()
